name: Lint

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - develop
      - production
      - testing
  pull_request:

jobs:
  lint:
    name: Lint
    uses: athombv/athom-github-workflow/.github/workflows/lint.yml@master
    secrets: inherit