name: Publish to GitHub Packages Registry

on:
  push:
    branches:
      - testing
      - production

jobs:
  release:
    name: Release
    runs-on: buildjet-2vcpu-ubuntu-2204-arm
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Setup Node.js
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e
        with:
          node-version-file: '.nvmrc'
          registry-url: 'https://npm.pkg.github.com'

      - name: Build
        run: |
          npm ci --audit=false
          npm run build
        env:
          NODE_AUTH_TOKEN: ${{ secrets.HOMEY_GITHUB_ACTIONS_BOT_PERSONAL_ACCESS_TOKEN }}

      # Sets package.json name & version to environment.
      - name: Get Package Info
        run: |
          NAME="$(node -p "require('./package.json').name")"
          echo package_name=${NAME} >> $GITHUB_ENV

          VERSION="$(node -p "require('./package.json').version")"
          echo package_version=${VERSION} >> $GITHUB_ENV

      # Publish when this action is running on branch production.
      - name: Publish
        if: github.ref == 'refs/heads/production'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish

      # Publish to beta when this action is running on branch testing.
      - name: Publish (beta)
        if: github.ref == 'refs/heads/testing'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npm publish --tag beta

        # Post a Slack notification on success/failure
      - name: Slack notify
        if: always()
        uses: innocarpe/actions-slack@0a7257df6b0ee9c03e24af13ad8b58709c50d3c1
        with:
          status: ${{ job.status }}
          success_text: '${{github.repository}} - Published ${{ env.package_name }}@${{ env.package_version }} to GitHub Packages Registry 🚀'
          failure_text: '${{github.repository}} - Failed to publish ${{ env.package_name }}@${{ env.package_version }} to GitHub Packages Registry'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
